extends:
  - react-app
  - airbnb
  - airbnb-typescript
parserOptions:
  project: ./tsconfig.json
rules:
  react/react-in-jsx-scope: off
  react/function-component-definition: off
  import/prefer-default-export: off
  consistent-return: off
  default-case: off
  no-plusplus: off
  no-underscore-dangle: ["error", { "allow": ["__typename"] }]
  react/require-default-props: off
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react/jsx-no-useless-fragment: off
