extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss

rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - global
  selector-class-pattern:
    - null
  scss/dollar-variable-pattern:
    - null
