
name: Build and push to documents s3
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the npm auth token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.APPS_pat }}" >> .npmrc

      - name: Install npm and build docs
        run: |
          npm install --legacy-peer-deps
          npm run docs

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: serverlessrepo-documents-s3bucket-b5otji3x0q78
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.DOCS_AWS_REGION }}
          SOURCE_DIR: "doc"
          DEST_DIR: apps/${{ secrets.APP_NAME }}

      - name: Invalidate cloudfront cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DOCS_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.DOCS_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
