
name: Invotra generate Github Issues
on: [push]

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        # Setup the node environment
      - name: Node.js setup
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.x
          always-auth: true
          scope: '@invotra'
          registry-url: https://npm.pkg.github.com/
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.5"
        id: "todo"
